Pooja
lightbulb-lms/lightbulb-lms-front-end pull request #2
Opened 2020-11-03 23:48 UTC by ManisshaMalapati

2020-11-03 23:49 UTC, ps11061601 commented
> _No description provided._

2020-11-04 00:20 UTC, chrisnellis approved these changes

2020-11-04 00:23 UTC, chrisnellis approved these changes

2020-11-04 00:32 UTC, ps11061601 approved these changes

2020-11-04 03:58 UTC, chrisnellis requested changes
Please add the guards before merging

2020-11-04 03:58 UTC, chrisnellis commented on src/app/app-routing.module.ts
> +    component: StudentHomePageComponent
If you want these pages to be protected by login, you can use:
`canActivate: [OktaAuthGuard],` in the route. 

That way, you can't access those pages without logging in first. I'd suggest you add them before merging

2020-11-04 08:14 UTC, chrisnellis commented
You can check this branch out [here](https://lightbulb-lms-front-end-git-pooja.lightbulb-lms.vercel.app/)

2020-11-30 22:53 UTC, chrisnellis approved these changes

2020-11-30 22:53 UTC, merged